# Server Config
server.port=8080

# Database Config
#spring.datasource.url=jdbc:postgresql://localhost:5432/ms_granter
#spring.datasource.username=postgres
#spring.datasource.password=root
spring.datasource.url=jdbc:postgresql://dpg-d96jjiei18ts739br2o0-a.oregon-postgres.render.com:5432/ms_granter?sslmode=require
spring.datasource.username=gaurav
spring.datasource.password=HfowpULm8AzTrYH37elTVLE2TMCy3Eny
# JPA Config
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# JWT Config
jwt.secret=mysupersecurejwtsecretkeythatismorethan32chars
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=grantersupport@gmail.com
spring.mail.password=tunf hyyx sgfx qhts

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account.sid=AC74842bb7fbed3f065082d7c882d8a581
twilio.auth.token=5de5ec1b98071cebd92b6578ff07d4a5
twilio.url=https://api.twilio.com/2010-04-01/Accounts/%s/Messages.json
twilio.from.number=+19863135363


konfir.url=https://api.konfir.com/verifications/v1
konfir.client-id=sandbox-74a4da15-9db4-4e7e-af21-f060a550d188
konfir.client-secret=MgeHS8j4n4RcwMMJbSN5x2xvK8bMz6eC

konfir.mete.redirect.url=https://www.konfir.com
konfir.mete.webhook.url=https://ms-granter.onrender.com/auth/webhook

sms.api.url=https://9jd293.api.infobip.com
sms.api.key=45c6b23f3e1a4f6584ee232e6a9e1733-7536a13e-cdea-461d-937f-44a21a4e8394
sms.sender=447491163443
