# Server Config
server.port=8080

# Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/ms_granter
spring.datasource.username=postgres
spring.datasource.password=root

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Config
jwt.secret=mysupersecurejwtsecretkeythatismorethan32chars
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=grantersupport@gmail.com
spring.mail.password=tunf hyyx sgfx qhts

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true