# Server Config
server.port=8080

# Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/ms_granter
spring.datasource.username=postgres
spring.datasource.password=root

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Config
jwt.secret=mysupersecurejwtsecretkeythatismorethan32chars
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=grantersupport@gmail.com
spring.mail.password=tunf hyyx sgfx qhts

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account.sid=AC5ffab742c330d4c6565a898751bbe1e9
twilio.auth.token=AC5ffab742c330d4c6565a898751bbe1e9
twilio.url=https://api.twilio.com/2010-04-01/Accounts/%s/Messages.json
twilio.from.number=+19783899473


konfir.url=https://api.konfir.com/verifications/v1
konfir.client-id=sandbox-74a4da15-9db4-4e7e-af21-f060a550d188
konfir.client-secret=MgeHS8j4n4RcwMMJbSN5x2xvK8bMz6eC
